// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: deliveryEntry.proto
// Protobuf Java Version: 4.29.2

package ru.sberbank.lab2ser.model;

public final class EntryProto {
  private EntryProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      EntryProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeliveryEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.DeliveryEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string market = 1;</code>
     * @return The market.
     */
    java.lang.String getMarket();
    /**
     * <code>string market = 1;</code>
     * @return The bytes for market.
     */
    com.google.protobuf.ByteString
        getMarketBytes();

    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    java.util.List<ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct> 
        getProductsList();
    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct getProducts(int index);
    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    int getProductsCount();
    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    java.util.List<? extends ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder> 
        getProductsOrBuilderList();
    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder getProductsOrBuilder(
        int index);

    /**
     * <code>string cardNumber = 3;</code>
     * @return The cardNumber.
     */
    java.lang.String getCardNumber();
    /**
     * <code>string cardNumber = 3;</code>
     * @return The bytes for cardNumber.
     */
    com.google.protobuf.ByteString
        getCardNumberBytes();

    /**
     * <code>double servicePercent = 4;</code>
     * @return The servicePercent.
     */
    double getServicePercent();
  }
  /**
   * Protobuf type {@code protobuf.DeliveryEntry}
   */
  public static final class DeliveryEntry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.DeliveryEntry)
      DeliveryEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 2,
        /* suffix= */ "",
        DeliveryEntry.class.getName());
    }
    // Use DeliveryEntry.newBuilder() to construct.
    private DeliveryEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DeliveryEntry() {
      market_ = "";
      products_ = java.util.Collections.emptyList();
      cardNumber_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.class, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.Builder.class);
    }

    public interface DeliveryProductOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.DeliveryEntry.DeliveryProduct)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>double cost = 1;</code>
       * @return The cost.
       */
      double getCost();

      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      java.lang.String getName();
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>string producer = 3;</code>
       * @return The producer.
       */
      java.lang.String getProducer();
      /**
       * <code>string producer = 3;</code>
       * @return The bytes for producer.
       */
      com.google.protobuf.ByteString
          getProducerBytes();

      /**
       * <code>string description = 4;</code>
       * @return The description.
       */
      java.lang.String getDescription();
      /**
       * <code>string description = 4;</code>
       * @return The bytes for description.
       */
      com.google.protobuf.ByteString
          getDescriptionBytes();

      /**
       * <code>int64 id = 5;</code>
       * @return The id.
       */
      long getId();
    }
    /**
     * Protobuf type {@code protobuf.DeliveryEntry.DeliveryProduct}
     */
    public static final class DeliveryProduct extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:protobuf.DeliveryEntry.DeliveryProduct)
        DeliveryProductOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 2,
          /* suffix= */ "",
          DeliveryProduct.class.getName());
      }
      // Use DeliveryProduct.newBuilder() to construct.
      private DeliveryProduct(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private DeliveryProduct() {
        name_ = "";
        producer_ = "";
        description_ = "";
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_DeliveryProduct_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_DeliveryProduct_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.class, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder.class);
      }

      public static final int COST_FIELD_NUMBER = 1;
      private double cost_ = 0D;
      /**
       * <code>double cost = 1;</code>
       * @return The cost.
       */
      @java.lang.Override
      public double getCost() {
        return cost_;
      }

      public static final int NAME_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private volatile java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PRODUCER_FIELD_NUMBER = 3;
      @SuppressWarnings("serial")
      private volatile java.lang.Object producer_ = "";
      /**
       * <code>string producer = 3;</code>
       * @return The producer.
       */
      @java.lang.Override
      public java.lang.String getProducer() {
        java.lang.Object ref = producer_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          producer_ = s;
          return s;
        }
      }
      /**
       * <code>string producer = 3;</code>
       * @return The bytes for producer.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getProducerBytes() {
        java.lang.Object ref = producer_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          producer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DESCRIPTION_FIELD_NUMBER = 4;
      @SuppressWarnings("serial")
      private volatile java.lang.Object description_ = "";
      /**
       * <code>string description = 4;</code>
       * @return The description.
       */
      @java.lang.Override
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        }
      }
      /**
       * <code>string description = 4;</code>
       * @return The bytes for description.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ID_FIELD_NUMBER = 5;
      private long id_ = 0L;
      /**
       * <code>int64 id = 5;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (java.lang.Double.doubleToRawLongBits(cost_) != 0) {
          output.writeDouble(1, cost_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(producer_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 3, producer_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 4, description_);
        }
        if (id_ != 0L) {
          output.writeInt64(5, id_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (java.lang.Double.doubleToRawLongBits(cost_) != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, cost_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(producer_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(3, producer_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(4, description_);
        }
        if (id_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(5, id_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct)) {
          return super.equals(obj);
        }
        ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct other = (ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct) obj;

        if (java.lang.Double.doubleToLongBits(getCost())
            != java.lang.Double.doubleToLongBits(
                other.getCost())) return false;
        if (!getName()
            .equals(other.getName())) return false;
        if (!getProducer()
            .equals(other.getProducer())) return false;
        if (!getDescription()
            .equals(other.getDescription())) return false;
        if (getId()
            != other.getId()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + COST_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getCost()));
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + PRODUCER_FIELD_NUMBER;
        hash = (53 * hash) + getProducer().hashCode();
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobuf.DeliveryEntry.DeliveryProduct}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protobuf.DeliveryEntry.DeliveryProduct)
          ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_DeliveryProduct_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_DeliveryProduct_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.class, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder.class);
        }

        // Construct using ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          cost_ = 0D;
          name_ = "";
          producer_ = "";
          description_ = "";
          id_ = 0L;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_DeliveryProduct_descriptor;
        }

        @java.lang.Override
        public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct getDefaultInstanceForType() {
          return ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.getDefaultInstance();
        }

        @java.lang.Override
        public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct build() {
          ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct buildPartial() {
          ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct result = new ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.cost_ = cost_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.name_ = name_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.producer_ = producer_;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            result.description_ = description_;
          }
          if (((from_bitField0_ & 0x00000010) != 0)) {
            result.id_ = id_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct) {
            return mergeFrom((ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct other) {
          if (other == ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.getDefaultInstance()) return this;
          if (other.getCost() != 0D) {
            setCost(other.getCost());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (!other.getProducer().isEmpty()) {
            producer_ = other.producer_;
            bitField0_ |= 0x00000004;
            onChanged();
          }
          if (!other.getDescription().isEmpty()) {
            description_ = other.description_;
            bitField0_ |= 0x00000008;
            onChanged();
          }
          if (other.getId() != 0L) {
            setId(other.getId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 9: {
                  cost_ = input.readDouble();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 9
                case 18: {
                  name_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                case 26: {
                  producer_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 26
                case 34: {
                  description_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000008;
                  break;
                } // case 34
                case 40: {
                  id_ = input.readInt64();
                  bitField0_ |= 0x00000010;
                  break;
                } // case 40
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private double cost_ ;
        /**
         * <code>double cost = 1;</code>
         * @return The cost.
         */
        @java.lang.Override
        public double getCost() {
          return cost_;
        }
        /**
         * <code>double cost = 1;</code>
         * @param value The cost to set.
         * @return This builder for chaining.
         */
        public Builder setCost(double value) {

          cost_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>double cost = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCost() {
          bitField0_ = (bitField0_ & ~0x00000001);
          cost_ = 0D;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 2;</code>
         * @return The name.
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          name_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearName() {
          name_ = getDefaultInstance().getName();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          name_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private java.lang.Object producer_ = "";
        /**
         * <code>string producer = 3;</code>
         * @return The producer.
         */
        public java.lang.String getProducer() {
          java.lang.Object ref = producer_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            producer_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string producer = 3;</code>
         * @return The bytes for producer.
         */
        public com.google.protobuf.ByteString
            getProducerBytes() {
          java.lang.Object ref = producer_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            producer_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string producer = 3;</code>
         * @param value The producer to set.
         * @return This builder for chaining.
         */
        public Builder setProducer(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          producer_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>string producer = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearProducer() {
          producer_ = getDefaultInstance().getProducer();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>string producer = 3;</code>
         * @param value The bytes for producer to set.
         * @return This builder for chaining.
         */
        public Builder setProducerBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          producer_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }

        private java.lang.Object description_ = "";
        /**
         * <code>string description = 4;</code>
         * @return The description.
         */
        public java.lang.String getDescription() {
          java.lang.Object ref = description_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            description_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string description = 4;</code>
         * @return The bytes for description.
         */
        public com.google.protobuf.ByteString
            getDescriptionBytes() {
          java.lang.Object ref = description_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            description_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string description = 4;</code>
         * @param value The description to set.
         * @return This builder for chaining.
         */
        public Builder setDescription(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          description_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }
        /**
         * <code>string description = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearDescription() {
          description_ = getDefaultInstance().getDescription();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }
        /**
         * <code>string description = 4;</code>
         * @param value The bytes for description to set.
         * @return This builder for chaining.
         */
        public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          description_ = value;
          bitField0_ |= 0x00000008;
          onChanged();
          return this;
        }

        private long id_ ;
        /**
         * <code>int64 id = 5;</code>
         * @return The id.
         */
        @java.lang.Override
        public long getId() {
          return id_;
        }
        /**
         * <code>int64 id = 5;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(long value) {

          id_ = value;
          bitField0_ |= 0x00000010;
          onChanged();
          return this;
        }
        /**
         * <code>int64 id = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000010);
          id_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protobuf.DeliveryEntry.DeliveryProduct)
      }

      // @@protoc_insertion_point(class_scope:protobuf.DeliveryEntry.DeliveryProduct)
      private static final ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct();
      }

      public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<DeliveryProduct>
          PARSER = new com.google.protobuf.AbstractParser<DeliveryProduct>() {
        @java.lang.Override
        public DeliveryProduct parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<DeliveryProduct> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<DeliveryProduct> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MARKET_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object market_ = "";
    /**
     * <code>string market = 1;</code>
     * @return The market.
     */
    @java.lang.Override
    public java.lang.String getMarket() {
      java.lang.Object ref = market_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        market_ = s;
        return s;
      }
    }
    /**
     * <code>string market = 1;</code>
     * @return The bytes for market.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMarketBytes() {
      java.lang.Object ref = market_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        market_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct> products_;
    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    @java.lang.Override
    public java.util.List<ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct> getProductsList() {
      return products_;
    }
    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder> 
        getProductsOrBuilderList() {
      return products_;
    }
    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    @java.lang.Override
    public int getProductsCount() {
      return products_.size();
    }
    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    @java.lang.Override
    public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct getProducts(int index) {
      return products_.get(index);
    }
    /**
     * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
     */
    @java.lang.Override
    public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder getProductsOrBuilder(
        int index) {
      return products_.get(index);
    }

    public static final int CARDNUMBER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cardNumber_ = "";
    /**
     * <code>string cardNumber = 3;</code>
     * @return The cardNumber.
     */
    @java.lang.Override
    public java.lang.String getCardNumber() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string cardNumber = 3;</code>
     * @return The bytes for cardNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCardNumberBytes() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICEPERCENT_FIELD_NUMBER = 4;
    private double servicePercent_ = 0D;
    /**
     * <code>double servicePercent = 4;</code>
     * @return The servicePercent.
     */
    @java.lang.Override
    public double getServicePercent() {
      return servicePercent_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(market_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, market_);
      }
      for (int i = 0; i < products_.size(); i++) {
        output.writeMessage(2, products_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cardNumber_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, cardNumber_);
      }
      if (java.lang.Double.doubleToRawLongBits(servicePercent_) != 0) {
        output.writeDouble(4, servicePercent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(market_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, market_);
      }
      for (int i = 0; i < products_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, products_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cardNumber_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, cardNumber_);
      }
      if (java.lang.Double.doubleToRawLongBits(servicePercent_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, servicePercent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry)) {
        return super.equals(obj);
      }
      ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry other = (ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry) obj;

      if (!getMarket()
          .equals(other.getMarket())) return false;
      if (!getProductsList()
          .equals(other.getProductsList())) return false;
      if (!getCardNumber()
          .equals(other.getCardNumber())) return false;
      if (java.lang.Double.doubleToLongBits(getServicePercent())
          != java.lang.Double.doubleToLongBits(
              other.getServicePercent())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MARKET_FIELD_NUMBER;
      hash = (53 * hash) + getMarket().hashCode();
      if (getProductsCount() > 0) {
        hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
        hash = (53 * hash) + getProductsList().hashCode();
      }
      hash = (37 * hash) + CARDNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getCardNumber().hashCode();
      hash = (37 * hash) + SERVICEPERCENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getServicePercent()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.DeliveryEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.DeliveryEntry)
        ru.sberbank.lab2ser.model.EntryProto.DeliveryEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.class, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.Builder.class);
      }

      // Construct using ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        market_ = "";
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
        } else {
          products_ = null;
          productsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        cardNumber_ = "";
        servicePercent_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.sberbank.lab2ser.model.EntryProto.internal_static_protobuf_DeliveryEntry_descriptor;
      }

      @java.lang.Override
      public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry getDefaultInstanceForType() {
        return ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.getDefaultInstance();
      }

      @java.lang.Override
      public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry build() {
        ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry buildPartial() {
        ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry result = new ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry result) {
        if (productsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            products_ = java.util.Collections.unmodifiableList(products_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.products_ = products_;
        } else {
          result.products_ = productsBuilder_.build();
        }
      }

      private void buildPartial0(ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.market_ = market_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.cardNumber_ = cardNumber_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.servicePercent_ = servicePercent_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry) {
          return mergeFrom((ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry other) {
        if (other == ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.getDefaultInstance()) return this;
        if (!other.getMarket().isEmpty()) {
          market_ = other.market_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (productsBuilder_ == null) {
          if (!other.products_.isEmpty()) {
            if (products_.isEmpty()) {
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureProductsIsMutable();
              products_.addAll(other.products_);
            }
            onChanged();
          }
        } else {
          if (!other.products_.isEmpty()) {
            if (productsBuilder_.isEmpty()) {
              productsBuilder_.dispose();
              productsBuilder_ = null;
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000002);
              productsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProductsFieldBuilder() : null;
            } else {
              productsBuilder_.addAllMessages(other.products_);
            }
          }
        }
        if (!other.getCardNumber().isEmpty()) {
          cardNumber_ = other.cardNumber_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getServicePercent() != 0D) {
          setServicePercent(other.getServicePercent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                market_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct m =
                    input.readMessage(
                        ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.parser(),
                        extensionRegistry);
                if (productsBuilder_ == null) {
                  ensureProductsIsMutable();
                  products_.add(m);
                } else {
                  productsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 26: {
                cardNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 33: {
                servicePercent_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object market_ = "";
      /**
       * <code>string market = 1;</code>
       * @return The market.
       */
      public java.lang.String getMarket() {
        java.lang.Object ref = market_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          market_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string market = 1;</code>
       * @return The bytes for market.
       */
      public com.google.protobuf.ByteString
          getMarketBytes() {
        java.lang.Object ref = market_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          market_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string market = 1;</code>
       * @param value The market to set.
       * @return This builder for chaining.
       */
      public Builder setMarket(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        market_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string market = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMarket() {
        market_ = getDefaultInstance().getMarket();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string market = 1;</code>
       * @param value The bytes for market to set.
       * @return This builder for chaining.
       */
      public Builder setMarketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        market_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct> products_ =
        java.util.Collections.emptyList();
      private void ensureProductsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          products_ = new java.util.ArrayList<ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct>(products_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder> productsBuilder_;

      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public java.util.List<ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct> getProductsList() {
        if (productsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(products_);
        } else {
          return productsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public int getProductsCount() {
        if (productsBuilder_ == null) {
          return products_.size();
        } else {
          return productsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct getProducts(int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);
        } else {
          return productsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public Builder setProducts(
          int index, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.set(index, value);
          onChanged();
        } else {
          productsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public Builder setProducts(
          int index, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.set(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public Builder addProducts(ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(value);
          onChanged();
        } else {
          productsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public Builder addProducts(
          int index, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(index, value);
          onChanged();
        } else {
          productsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public Builder addProducts(
          ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public Builder addProducts(
          int index, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public Builder addAllProducts(
          java.lang.Iterable<? extends ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct> values) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, products_);
          onChanged();
        } else {
          productsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public Builder clearProducts() {
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          productsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public Builder removeProducts(int index) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.remove(index);
          onChanged();
        } else {
          productsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder getProductsBuilder(
          int index) {
        return getProductsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder getProductsOrBuilder(
          int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);  } else {
          return productsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public java.util.List<? extends ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder> 
           getProductsOrBuilderList() {
        if (productsBuilder_ != null) {
          return productsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(products_);
        }
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder addProductsBuilder() {
        return getProductsFieldBuilder().addBuilder(
            ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder addProductsBuilder(
          int index) {
        return getProductsFieldBuilder().addBuilder(
            index, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.DeliveryEntry.DeliveryProduct products = 2;</code>
       */
      public java.util.List<ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder> 
           getProductsBuilderList() {
        return getProductsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder> 
          getProductsFieldBuilder() {
        if (productsBuilder_ == null) {
          productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProduct.Builder, ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry.DeliveryProductOrBuilder>(
                  products_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          products_ = null;
        }
        return productsBuilder_;
      }

      private java.lang.Object cardNumber_ = "";
      /**
       * <code>string cardNumber = 3;</code>
       * @return The cardNumber.
       */
      public java.lang.String getCardNumber() {
        java.lang.Object ref = cardNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cardNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cardNumber = 3;</code>
       * @return The bytes for cardNumber.
       */
      public com.google.protobuf.ByteString
          getCardNumberBytes() {
        java.lang.Object ref = cardNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cardNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cardNumber = 3;</code>
       * @param value The cardNumber to set.
       * @return This builder for chaining.
       */
      public Builder setCardNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cardNumber_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string cardNumber = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCardNumber() {
        cardNumber_ = getDefaultInstance().getCardNumber();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string cardNumber = 3;</code>
       * @param value The bytes for cardNumber to set.
       * @return This builder for chaining.
       */
      public Builder setCardNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cardNumber_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private double servicePercent_ ;
      /**
       * <code>double servicePercent = 4;</code>
       * @return The servicePercent.
       */
      @java.lang.Override
      public double getServicePercent() {
        return servicePercent_;
      }
      /**
       * <code>double servicePercent = 4;</code>
       * @param value The servicePercent to set.
       * @return This builder for chaining.
       */
      public Builder setServicePercent(double value) {

        servicePercent_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double servicePercent = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearServicePercent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        servicePercent_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.DeliveryEntry)
    }

    // @@protoc_insertion_point(class_scope:protobuf.DeliveryEntry)
    private static final ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry();
    }

    public static ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeliveryEntry>
        PARSER = new com.google.protobuf.AbstractParser<DeliveryEntry>() {
      @java.lang.Override
      public DeliveryEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DeliveryEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeliveryEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.sberbank.lab2ser.model.EntryProto.DeliveryEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_DeliveryEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_DeliveryEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_DeliveryEntry_DeliveryProduct_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_DeliveryEntry_DeliveryProduct_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023deliveryEntry.proto\022\010protobuf\"\350\001\n\rDeli" +
      "veryEntry\022\016\n\006market\030\001 \001(\t\0229\n\010products\030\002 " +
      "\003(\0132\'.protobuf.DeliveryEntry.DeliveryPro" +
      "duct\022\022\n\ncardNumber\030\003 \001(\t\022\026\n\016servicePerce" +
      "nt\030\004 \001(\001\032`\n\017DeliveryProduct\022\014\n\004cost\030\001 \001(" +
      "\001\022\014\n\004name\030\002 \001(\t\022\020\n\010producer\030\003 \001(\t\022\023\n\013des" +
      "cription\030\004 \001(\t\022\n\n\002id\030\005 \001(\003B\'\n\031ru.sberban" +
      "k.lab2ser.modelB\nEntryProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_DeliveryEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_DeliveryEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_DeliveryEntry_descriptor,
        new java.lang.String[] { "Market", "Products", "CardNumber", "ServicePercent", });
    internal_static_protobuf_DeliveryEntry_DeliveryProduct_descriptor =
      internal_static_protobuf_DeliveryEntry_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_DeliveryEntry_DeliveryProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_DeliveryEntry_DeliveryProduct_descriptor,
        new java.lang.String[] { "Cost", "Name", "Producer", "Description", "Id", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
